services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www/html
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    networks:
      - ah_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ah_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ah_network

  frontend:
    image: node:22
    container_name: frontend
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run watch"
    profiles:
      - dev
    networks:
      - ah_network
    depends_on:
      - app

volumes:
  db_data: null

networks:
  ah_network: